language: node_js
os:
  - windows
  - linux
node_js:
  - "8"
  - "10"
  - "11"
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run coverage-all
after_success:
  - npm install codecov
  - npm run report-coverage
